package com.example.electricityproject.data.sqlite;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.electricityproject.data.table.Shop;
import com.example.electricityproject.data.table.Flow;

import com.example.electricityproject.data.sqlite.ShopDao;
import com.example.electricityproject.data.sqlite.FlowDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig shopDaoConfig;
    private final DaoConfig flowDaoConfig;

    private final ShopDao shopDao;
    private final FlowDao flowDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        shopDaoConfig = daoConfigMap.get(ShopDao.class).clone();
        shopDaoConfig.initIdentityScope(type);

        flowDaoConfig = daoConfigMap.get(FlowDao.class).clone();
        flowDaoConfig.initIdentityScope(type);

        shopDao = new ShopDao(shopDaoConfig, this);
        flowDao = new FlowDao(flowDaoConfig, this);

        registerDao(Shop.class, shopDao);
        registerDao(Flow.class, flowDao);
    }
    
    public void clear() {
        shopDaoConfig.clearIdentityScope();
        flowDaoConfig.clearIdentityScope();
    }

    public ShopDao getShopDao() {
        return shopDao;
    }

    public FlowDao getFlowDao() {
        return flowDao;
    }

}
